version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: churchManagement-postgresql-1
    env_file: ./env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Certifique-se de que o caminho correto está sendo usado
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"  # Mapeie a porta 5432 do contêiner para a porta 5433 no host

  app:
    build:
      context: .
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: